version: "3.2"
services:
  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: dockerfile-elasticsearch
    ports:
      - "9200:9200"
    depends_on:
      - fluentd
  fluentd:
    build:
      context: ./fluentd
      dockerfile: dockerfile-fluentd
    ports:
      - "24224:24224"
  web:
    build:
      context: ./web
      dockerfile: dockerfile-web
    volumes:
      - ./web/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        tag: "web"
        fluentd-address: "localhost:24224"
    ports:
      - "80:80"
